<?php

/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE! DO NOT COPY prefs.php TO prefs.local.php!
 * Local overrides ONLY MUST be placed in var/config/chora/prefs.local.php or
 * var/config/chora/prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/chora/prefs-servername.php.
 */

// last browse file/directory
$_prefs['last_file'] = [
    'value' => 0,
];

// last sourceroot used
$_prefs['last_sourceroot'] = [
    'value' => 0,
];
